# Change these first
owner: sbamniya # Your GitHub organization or username, where this repository lives
repo: zestnexus-status # The name of this repository

sites:
  - name: ZestNexus Website
    url: https://www.zestnexus.com
  - name: ZestNexus App
    url: https://app.zestnexus.com
  - name: APIs
    url: https://api.zestnexus.com
  - name: Client App
    url: http://clients.zestnexus.com
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.zestnexus.com
  #baseUrl: /zestnexus-status
  logoUrl: https://www.zestnexus.com/logo.png
  name: ZestNexus
  introTitle: "All-in-one platform for your business"
  introMessage: ZestNexus provides an all-in-one solution designed to save time, reduce costs, and enhance productivity. We help you simplify your business operations with modern, intuitive, and customizable software.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
